graph: data/DBLP/dblp-2015-2017.ttl
method: pglove
dim: 300
#threads: 1
weights:
  http://xmlns.com/foaf/0.1/name: 1
  http://purl.org/dc/terms/references: 1
  http://purl.org/dc/elements/1.1/title: 1
  http://purl.org/dc/elements/1.1/creator: 1
similarity:
  - predicate: http://xmlns.com/foaf/0.1/name
    method: jarowinkler
    threshold: 0.95
  - predicate: http://purl.org/dc/elements/1.1/title
    method: token
    threshold: 0.5
bca:
  alpha: 1e-1
  epsilon: 1e-3
  reverse: true
  directed: true
  predicates: true
opt:
  method: adagrad
  tolerance: 1e-4
  maxiter: 1000
pca:
  variance: 0.95
output:
  uri: [ http://dblp.l3s.de/d2r/resource/authors/ ]
  #predicate: []
  #blank: []
  #literal: []
