graph: data/Onstage/onstage.nt
method: pglove
dim: 300
#threads: 3
weights:
  #http://www.w3.org/1999/02/22-rdf-syntax-ns#type: 1
  #http://www.w3.org/2002/07/owl#sameAs: 1
  #http://www.w3.org/ns/md#item: 1
  #http://schema.org/sameAs: 1
  http://schema.org/exampleOfWork: 1
  http://schema.org/workPerformed: 0.1
  #http://schema.org/location: 1
  #http://schema.org/addressLocality: 1
  #http://schema.org/position: 1
  http://schema.org/subEvent: 0.1
  http://schema.org/startDate: 1
  http://schema.org/name: 1
  http://schema.org/isBasedOn: 1
  http://schema.org/inLanguage: 1
  http://schema.org/creator: 1
  http://schema.org/dateCreated: 1
  http://schema.org/headline: 1
similarity:
  - predicate: http://schema.org/name
    method: jarowinkler
    threshold: 0.8
  - predicate: http://schema.org/headline
    method: jaccard
    ngram: 4
    threshold: 0.75
bca:
  alpha: 1e-1
  epsilon: 1e-3
  reverse: true
  directed: true
  predicates: true
opt:
  method: adagrad
  tolerance: 1e-4
  maxiter: 1000
pca:
  variance: 0.95
output:
  uri: [ http://www.vondel.humanities.uva.nl/onstage/persons/, http://www.vondel.humanities.uva.nl/onstage/plays/ ]
  #predicate: []
  #blank: []
  #literal: []

