graph: data/DBLP/dblp_2015-2015.hdt
method: glove
dim: 50
prefixes:
  dblp: http://dblp.l3s.de/d2r/resource/
predicates:
  type: MANUAL
  filter:
    [
      #dblp:name,
      dblp:author,
      #dblp:title
    ]
  weights:
    dblp:author: 1
similarityGroups:
  - sourceType: dblp:Author
    targetType: dblp:Author
    threshold: 0.8
    resultFunction: HRM
    similarities:
      - sourcePredicate: dblp:name
        targetPredicate: dblp:name
        method: LEVENSHTEIN
        threshold: 0.8
      - sourcePredicate: ^dblp:author/dblp:title
        targetPredicate: ^dblp:author/dblp:title
        method: TOKEN_COSINE
        threshold: 0.8
bca:
  alpha: 1e-2
  epsilon: 1e-3
opt:
  method: amsgrad
  tolerance: 1e-6
  maxiter: 1000
output:
  name: dblp_embedding
  writer: glove
  type: [dblp:Author]

