graph: data/DBLP/dblp_2015-2015.ttl
method: glove
dim: 50
predicates:
  type: MANUAL
  filter:
    [ dblp:name,
      dblp:author,
      dblp:title ]
  weights:
    dblp:name: 10
similarity:
  - sourceType: dblp:Author
    targetType: dblp:Author
    sourcePredicate: dblp:name
    targetPredicate: dblp:name
    method: LEVENSHTEIN
    threshold: 0.80
  - sourceType: dblp:Publication
    targetType: dblp:Publication
    sourcePredicate: dblp:title
    targetPredicate: dblp:title
    method: TOKEN_COSINE
    threshold: 0.8
bca:
  alpha: 1e-2
  epsilon: 1e-3
opt:
  method: amsgrad
  tolerance: 1e-6
  maxiter: 1000
output:
  name: dblp_embedding
  writer: glove
  type: [dblp:Author]

