graph: data/SAA/saa.hdt
method: glove
dim: 100
prefixes:
  saa: http://goldenagents.org/uva/SAA/ontology/
predicates:
  type: MANUAL
  filter: [
    #saa:full_name,
    #saa:family_name,
    #saa:first_name,
    #saa:church,
    #saa:religion,
    #saa:burial_date_approx,
    #saa:baptism_date_approx,
    #saa:marriage_date_approx,
    #saa:prenuptial_marriage_date_approx,
    #saa:birth_date_approx,
    #saa:death_date_approx,
    saa:isInRecord,
    #saa:mentionsFather,
    #saa:mentionsMother,
    #saa:mentionsBride,
    #saa:mentionsGroom,
    #saa:mentionsPreviousHusband,
    #saa:mentionsPreviousWife
  ]
  weights:
    saa:isInRecord: .1
similarityGroups:
  - sourceType: saa:Person
    targetType: saa:Person
    threshold: 0.9
    resultFunction: HRM
    conditions:
      - sourcePredicate: saa:birth_date_approx|(saa:isInRecord/saa:marriage_date_approx)
        targetPredicate: saa:death_date_approx|(saa:isInRecord/saa:burial_date_approx)
        pattern: yyyy-MM-dd
        method: BEFORE
      - sourcePredicate: saa:isInRecord/saa:baptism_date_approx
        targetPredicate: saa:death_date_approx|(saa:isInRecord/saa:burial_date_approx)
        pattern: yyyy-MM-dd
        method: BEFORE
      - sourcePredicate: saa:isInRecord/saa:baptism_date_approx
        targetPredicate: (saa:isInRecord/saa:prenuptial_marriage_date_approx)|(saa:isInRecord/saa:marriage_date_approx)
        pattern: yyyy-MM-dd
        method: BEFORE
      - sourcePredicate: saa:isInRecord/saa:prenuptial_marriage_date_approx
        targetPredicate: saa:isInRecord/saa:marriage_date_approx
        pattern: yyyy-MM-dd
        method: BEFORE
    similarities:
      - sourcePredicate: saa:full_name
        targetPredicate: saa:full_name
        method: LEVENSHTEIN
        threshold: 0.9
      - sourcePredicate: saa:isInRecord/saa:prenuptial_marriage_date_approx
        targetPredicate: saa:isInRecord/saa:marriage_date_approx
        method: DATE_DAYS
        pattern: yyyy-MM-dd
        time: FORWARDS
        threshold: 0.9
        thresholdDistance: 6
        offset: 18
        optional: true
      - sourcePredicate: saa:death_date_approx
        targetPredicate: saa:isInRecord/saa:burial_date_approx
        method: DATE_DAYS
        pattern: yyyy-MM-dd
        time: FORWARDS
        threshold: 0.9
        thresholdDistance: 2
        offset: 1
        optional: true
bca:
  alpha: 1e-3
  epsilon: 1e-4
opt:
  method: amsgrad
  tolerance: 1e-6
  maxiter: 1000
output:
  name: saa_embedding
  writer: glove
  type: [saa:Person]

